### ISSUE TITLE
pytest tests/unit_tests/test_simulator.py::test_submitting fails (locally)

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/simtools#494] opened 2023-07-18 12:16 UTC
See attached log files with all the errors.

This is for running locally in a conda environment without (!) a simtel_array installation.

If the missing simtel is the reason: should unit tests notice this and be skipped or better fail like in this case?

[test_error.log](https://github.com/gammasim/simtools/files/12080277/test_error.log)

**Comment by VictorBarbosaMartins** [comment] 2023-07-18 14:53
Hi.
I think failing is good, since it is testing the simulator itself (which depends on simtel_array). I would though prefer to treat the error and try to indicate in the error message that the problem is the missing simtel_array installation

**Comment by GernotMaier** [comment] 2023-07-19 07:20
A lot of our applications do not need simtel_array, and I think we should allow to run pytests without the simulation software (as we want to test simtools).

**Comment by VictorBarbosaMartins** [comment] 2023-07-19 07:34
agreed. but we test applications through the integration tests. the unit tests should be dedicated tests. in any case, I think you are right. If this specific unit test needs the simtel_array installation to test a minimal function, we can skip the test if the installation is not there. However, it is important to have a dedicated test that fails if the installation is not there, which would probably make sense to have in the tests for the container, as we spoke yesterday.

**Comment by GernotMaier** [comment] 2023-07-19 07:47
This is a different discussion. What we need is that tests are running without sim_telarray / corsika installation.

**Comment by orelgueta** [comment] 2023-07-19 13:33
Quick answer (partly so that I don't forget as well), the issue is indeed that sim_telarray isn't available and the current plan is to simply skip this test (and perhaps others) if it doesn't. Fairly easy to implement, just need to make sure that we want to skip the test and not perhaps modify it to test stuff around running sim_telarray.

**Comment by orelgueta** [comment] 2023-07-20 10:15
Wow, that took a turn...

Forget the earlier explanation, this error has nothing to do with sim_telarray being present or not. I will explain here the full chain of events (even if it's not interesting, I wasted half of the morning on this so I need to write about it).

- The error itself is the result of a bug in the `test_submitting` function where we did not set the simulator to a test run without actually trying to run sim_telarray (this is a unit test, not an integration test). This bug led to the script calling sim_telarray to actually be called.
- We never saw this error on ubuntu because the script which is called when "submitting" has a few lines in it and the last line which reports the exit code is a simple `echo`. Therefore, we always got a successful run exit code (another bug). This will be fixed in a PR now, where each call is checked if it succeeded, not just the last one.
- We did notice this error on mac because the scripts we produce to run sim_telarray had the following shebang `/usr/bin/bash`. That fails on MacOS so we always got a non-zero exit code. This is also fixed now, using a more portable shebang.

This teaches us that we should test on various systems regardless if we want to run on them, just to find these weird bugs...

**Closed** 2023-07-24 08:16 UTC
